export const mockTableBlock = `#Контент
title_text: "Заголовок"
column_title_1: "Заголовок столбца 1"
column_title_2: "Заголовок столбца 2"
column_title_3: "Заголовок столбца 3"
column_title_4: "Заголовок столбца 4"
rows: [{img: "https://cdn.example.com/builder/images/templates/card_image.svg", text_1: "Текст 1", text_2: "Текст 2", text_3: "Текст 3", text_4: "Текст 4"}, {img: "https://cdn.example.com/builder/images/templates/card_image.svg", text_1: "Текст 1", text_2: "Текст 2", text_3: "Текст 3", text_4: "Текст 4"}, {img: "https://cdn.example.com/builder/images/templates/card_image.svg", text_1: "Текст 1", text_2: "Текст 2", text_3: "Текст 3", text_4: "Текст 4"}]
#Общее
section_container: "container"
section_columns: "10"
section_padding_top: "50"
section_padding_bottom: "50"
section_bg_color: "rgb(255, 255, 255)"
section_bg_image: ""
table_padding_top: "5"
table_padding_bottom: "5"
table_padding_sides: "5"
tablet_section_padding_top: "30"
tablet_section_padding_bottom: "30"
tablet_table_padding_top: "5"
tablet_table_padding_bottom: "5"
phone_section_padding_top: "20"
phone_section_padding_bottom: "20"
phone_section_bg_color: "rgb(255, 255, 255)"
phone_section_bg_image: ""
phone_table_padding_top: "5"
phone_table_padding_bottom: "5"
#Заголовок
title_font_family: "'Montserrat', sans-serif"
title_font_size: "52"
title_font_weight: "700"
title_line_height: "1"
title_color: "rgb(148, 152, 159)"
title_align: "center"
title_margin_bottom: "40"
tablet_title_font_size: "46"
tablet_title_margin_bottom: "40"
phone_title_font_size: "27"
phone_title_margin_bottom: "20"
#Заголовки таблицы
header_font_family: "'Montserrat', sans-serif"
header_font_size: "20"
header_font_weight: "500"
header_color: "rgb(148, 152, 159)"
header_align: "center"
tablet_header_font_size: "12"
tablet_header_align: "center"
phone_header_font_size: "12"
phone_header_align: "center"
#Текст таблицы
text_font_family: "'Montserrat', sans-serif"
text_font_size: "18"
text_font_weight: "400"
text_line_height: "1"
text_color: "rgb(148, 152, 159)"
text_align: "center"
tablet_text_font_size: "12"
tablet_text_line_height: "1"
tablet_text_align: "center"
phone_text_font_size: "12"
phone_text_line_height: "1"
phone_text_align: "left"
#Количество столбцов
count_col: "5"
#Изображение
image_height: "150"
tablet_image_height: "150"
phone_image_height: "200"
#Контролы
widgets_controls: {title_text: {group: "Заголовок", name: "Заголовок", type: "wysiwyg"}, column_title_1: {group: "Заголовки таблицы", name: "Заголовок столбца 1", type: "wysiwyg"}, column_title_2: {group: "Заголовки таблицы", name: "Заголовок столбца 2", type: "wysiwyg"}, column_title_3: {group: "Заголовки таблицы", name: "Заголовок столбца 3", type: "wysiwyg"}, column_title_4: {group: "Заголовки таблицы", name: "Заголовок столбца 4", type: "wysiwyg"}, rows: {group: "Строки", name: "Строка", type: "collection", template: {img: {type: "file", name: "Изображение", max_size: "204800", file_types: "image/jpeg,image/png,image/gif,image/svg+xml"}, text_1: {type: "wysiwyg", name: "Текст 1"}, text_2: {type: "wysiwyg", name: "Текст 2"}, text_3: {type: "wysiwyg", name: "Текст 3"}, text_4: {type: "wysiwyg", name: "Текст 4"}}}, section_container: {group: "Общее", name: "Тип контейнера", type: "radio", options: {"Обычный": "container", "На всю ширину": "container-fluid"}, builder_kind: "design-desktop"}, section_columns: {group: "Общее", name: "Ширина блока", type: "range", min: 6, max: 12, builder_kind: "design-desktop"}, section_padding_top: {group: "Общее", name: "Отступ сверху (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, section_padding_bottom: {group: "Общее", name: "Отступ снизу (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_section_padding_top: {group: "Общее", name: "Отступ сверху (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, tablet_section_padding_bottom: {group: "Общее", name: "Отступ снизу (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_section_padding_top: {group: "Общее", name: "Отступ сверху (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, phone_section_padding_bottom: {group: "Общее", name: "Отступ снизу (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, section_bg_color: {group: "Общее", name: "Цвет фона", type: "color", builder_kind: "design-desktop"}, phone_section_bg_color: {group: "Общее", name: "Цвет фона", type: "color", builder_kind: "design-phone"}, section_bg_image: {group: "Общее", name: "Фоновое изображение", type: "file", file_types: "image/jpeg,image/png", max_size: "819200", builder_kind: "design-desktop"}, phone_section_bg_image: {group: "Общее", name: "Фоновое изображение", type: "file", file_types: "image/jpeg,image/png", max_size: "819200", builder_kind: "design-phone"}, table_padding_top: {group: "Общее", name: "Отступ сверху в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, table_padding_bottom: {group: "Общее", name: "Отступ снизу в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, table_padding_sides: {group: "Общее", name: "Отступ по бокам в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_table_padding_top: {group: "Общее", name: "Отступ сверху в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, tablet_table_padding_bottom: {group: "Общее", name: "Отступ снизу в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_table_padding_top: {group: "Общее", name: "Отступ сверху в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, phone_table_padding_bottom: {group: "Общее", name: "Отступ снизу в ячейках (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, count_col: {group: "Общее", name: "Количество столбцов", type: "select", options: {"2": "2", "3": "3", "4": "4", "5": "5"}, builder_kind: "design-desktop"}, title_font_family: {group: "Заголовок", name: "Шрифт", type: "fonts", builder_kind: "design-desktop"}, title_font_size: {group: "Заголовок", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_title_font_size: {group: "Заголовок", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_title_font_size: {group: "Заголовок", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, title_font_weight: {group: "Заголовок", name: "Жирность шрифта", type: "radio", options: {"light": "300", "normal": "400", "medium": "500", "bold": "700"}, builder_kind: "design-desktop"}, title_line_height: {group: "Заголовок", name: "Межстрочный интервал", type: "textfield", builder_kind: "design-desktop"}, title_color: {group: "Заголовок", name: "Цвет текста", type: "color", builder_kind: "design-desktop"}, title_align: {group: "Заголовок", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-desktop"}, title_margin_bottom: {group: "Заголовок", name: "Отступ снизу (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_title_margin_bottom: {group: "Заголовок", name: "Отступ снизу (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_title_margin_bottom: {group: "Заголовок", name: "Отступ снизу (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, image_height: {group: "Изображение", name: "Максимальная высота (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_image_height: {group: "Изображение", name: "Максимальная высота (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_image_height: {group: "Изображение", name: "Максимальная высота (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, header_font_family: {group: "Заголовки таблицы", name: "Шрифт", type: "fonts", builder_kind: "design-desktop"}, header_font_size: {group: "Заголовки таблицы", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_header_font_size: {group: "Заголовки таблицы", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_header_font_size: {group: "Заголовки таблицы", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, header_font_weight: {group: "Заголовки таблицы", name: "Жирность шрифта", type: "radio", options: {"light": "300", "normal": "400", "medium": "500", "bold": "700"}, builder_kind: "design-desktop"}, header_color: {group: "Заголовки таблицы", name: "Цвет текста", type: "color", builder_kind: "design-desktop"}, header_align: {group: "Заголовки таблицы", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-desktop"}, tablet_header_align: {group: "Заголовки таблицы", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-tablet"}, phone_header_align: {group: "Заголовки таблицы", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-phone"}, text_font_family: {group: "Текст таблицы", name: "Шрифт", type: "fonts", builder_kind: "design-desktop"}, text_font_size: {group: "Текст таблицы", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-desktop"}, tablet_text_font_size: {group: "Текст таблицы", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-tablet"}, phone_text_font_size: {group: "Текст таблицы", name: "Размер шрифта (в px)", type: "textfield", validate: {digits: "true"}, builder_kind: "design-phone"}, text_font_weight: {group: "Текст таблицы", name: "Жирность шрифта", type: "radio", options: {"light": "300", "normal": "400", "medium": "500", "bold": "700"}, builder_kind: "design-desktop"}, text_line_height: {group: "Текст таблицы", name: "Межстрочный интервал", type: "textfield", builder_kind: "design-desktop"}, text_color: {group: "Текст таблицы", name: "Цвет текста", type: "color", builder_kind: "design-desktop"}, tablet_text_line_height: {group: "Текст таблицы", name: "Межстрочный интервал", type: "textfield", builder_kind: "design-tablet"}, tablet_text_align: {group: "Текст таблицы", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-tablet"}, phone_text_line_height: {group: "Текст таблицы", name: "Межстрочный интервал", type: "textfield", builder_kind: "design-phone"}, text_align: {group: "Текст таблицы", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-desktop"}, phone_text_align: {group: "Текст таблицы", name: "Выравнивание", type: "radio", options: {"Слева": "left", "По центру": "center", "Справа": "right"}, builder_kind: "design-phone"}}
`
